(async()=>{'use strict';
const B=window.DeMovementBackend,$=s=>document.querySelector(s),root=$('#admin-root');
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let profiles=[],rels=[],pilot=null,view='people';
if(B.mode!=='supabase'){root.innerHTML='<section class="card"><p class="notice">Administrator tools require the cloud backend.</p></section>';return}
const sess=await B.session();if(!sess){location.replace('account.html?next=administrator.html');return}
const me=await B.me();if(me?.role!=='administrator'||me.account_status!=='active'){location.replace('account.html');return}
async function refresh(){[profiles,rels,pilot]=await Promise.all([B.administratorProfiles(),B.administratorRelationships(),B.administratorPilotMetrics()]);render()}
function metrics(){return `<div class="metrics"><div class="metric"><span>MOVERS</span><strong>${profiles.filter(x=>x.role==='mover').length}</strong></div><div class="metric"><span>COACHES</span><strong>${profiles.filter(x=>x.role==='coach').length}</strong></div><div class="metric"><span>ADMINISTRATORS</span><strong>${profiles.filter(x=>x.role==='administrator').length}</strong></div><div class="metric"><span>ACTIVE RELATIONSHIPS</span><strong>${rels.filter(x=>x.status==='active').length}</strong></div></div>`}
function people(){return `<section class="card"><div class="tablewrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th>Controls</th></tr></thead><tbody>${profiles.map(p=>`<tr><td><b>${esc(p.display_name)}</b></td><td>${esc(p.email||'')}</td><td><span class="status">${esc(p.role)}</span></td><td><span class="status ${esc(p.account_status)}">${esc(p.account_status)}</span></td><td><div class="actions">${p.id===me.id?'<span class="status">Current Admin</span>':`<select class="field role-change" data-id="${p.id}"><option value="mover" ${p.role==='mover'?'selected':''}>Mover</option><option value="coach" ${p.role==='coach'?'selected':''}>Coach</option><option value="administrator" ${p.role==='administrator'?'selected':''}>Administrator</option></select><button class="btn status-toggle" data-id="${p.id}" data-next="${p.account_status==='suspended'?'active':'suspended'}">${p.account_status==='suspended'?'Reactivate':'Suspend'}</button>`}</div></td></tr>`).join('')}</tbody></table></div></section>`}
function relationships(){const coaches=profiles.filter(x=>x.role==='coach'&&x.account_status==='active');return `<section class="card"><div class="tablewrap"><table><thead><tr><th>Mover</th><th>Coach</th><th>Status</th><th>Created</th><th>Transfer</th></tr></thead><tbody>${rels.map(r=>`<tr><td><b>${esc(r.mover?.display_name||r.mover_id)}</b></td><td>${esc(r.coach?.display_name||r.coach_id)}</td><td><span class="status ${esc(r.status)}">${esc(r.status)}</span></td><td>${new Date(r.created_at).toLocaleDateString('en-AU')}</td><td><select class="field transfer" data-id="${r.id}"><option value="">Choose Coach…</option>${coaches.map(c=>`<option value="${c.id}">${esc(c.display_name)}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="5">No relationships yet.</td></tr>'}</tbody></table></div></section>`}
function pilotView(){
 const p=pilot||{};
 return `<div class="grid">
  <section class="card"><p class="eyebrow">PILOT SIGNALS</p><h2>Use the data people intentionally create.</h2><p class="lead">No hidden clickstream is required. These metrics come from synced training, readiness, Passport/Flow use and explicit feedback.</p>
   <div class="metrics"><div class="metric"><span>ACTIVE MOVERS · 7D</span><strong>${p.activeMovers7||0}</strong></div><div class="metric"><span>TRAINING LOGS · 7D</span><strong>${p.sessions7||0}</strong></div><div class="metric"><span>TRAINING LOGS · 30D</span><strong>${p.sessions30||0}</strong></div><div class="metric"><span>FLOW LOGS · 30D</span><strong>${p.flowLogs30||0}</strong></div></div>
   <div class="metrics"><div class="metric"><span>PASSPORT USERS</span><strong>${p.passportUsers||0}</strong></div><div class="metric"><span>SAVED FLOWS</span><strong>${p.savedFlows||0}</strong></div><div class="metric"><span>READINESS · 30D</span><strong>${p.readiness30||0}</strong></div><div class="metric"><span>FEEDBACK AVG</span><strong>${p.feedbackAverage||'–'}</strong></div></div>
   <div class="mini-grid"><div class="mini"><span>EFFORT · 30D</span><b>${p.averageEffort30||'–'}</b></div><div class="mini"><span>CONTROL · 30D</span><b>${p.averageControl30||'–'}</b></div><div class="mini"><span>CONFIDENCE · 30D</span><b>${p.averageConfidence30||'–'}</b></div></div>
  </section>
  <section class="card"><p class="eyebrow">EXPLICIT FEEDBACK</p><h2>What pilot users told us</h2><div class="activity">${(p.feedback||[]).map(x=>`<article><b>${esc(x.area)} · ${x.rating}/5</b><small>${new Date(x.created_at).toLocaleString('en-AU')} · build ${esc(x.build)}</small><p style="margin:7px 0 0">${esc(x.comment)}</p></article>`).join('')||'<p class="notice">No submitted pilot feedback yet.</p>'}</div></section>
 </div>`;
}
function bind(){
 document.querySelectorAll('.role-change').forEach(s=>s.onchange=async()=>{if(!confirm('Change this account role to '+s.value+'?'))return refresh();try{await B.administratorSetRole(s.dataset.id,s.value);await refresh()}catch(e){alert(e.message);await refresh()}});
 document.querySelectorAll('.status-toggle').forEach(b=>b.onclick=async()=>{if(!confirm((b.dataset.next==='suspended'?'Suspend':'Reactivate')+' this account?'))return;try{await B.administratorSetAccountStatus(b.dataset.id,b.dataset.next);await refresh()}catch(e){alert(e.message)}});
 document.querySelectorAll('.transfer').forEach(s=>s.onchange=async()=>{if(!s.value)return;if(!confirm('Transfer this Mover to the selected Coach?'))return render();try{await B.administratorTransferMover(s.dataset.id,s.value);await refresh()}catch(e){alert(e.message)}});
}
function render(){
 root.innerHTML=metrics()+`<div class="tabs"><button class="${view==='people'?'active':''}" data-tab="people">People</button><button class="${view==='relationships'?'active':''}" data-tab="relationships">Coach ↔ Mover</button><button class="${view==='pilot'?'active':''}" data-tab="pilot">Pilot</button></div>`+(view==='people'?people():view==='relationships'?relationships():pilotView());
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{view=b.dataset.tab;render()});bind()
}
await refresh();
})().catch(e=>{document.querySelector('#admin-root').innerHTML='<section class="card"><p class="notice bad">'+String(e.message||e)+'</p></section>'});